#A Service provides a stable network endpoint for accessing Pods.
#Pods can be created, deleted, and recreated at any time, so their IP addresses change.
#A Service solves this by providing:
#Stable IP address
#Stable DNS name
#Load balancing across Pods
#Communication between applications
#Instead of connecting directly to Pods, clients connect to the Service.
#ClusterIP (Default):Used for communication between applications inside Kubernetes.
#NodePort: Exposes application outside the cluster.
#LoadBalancer: Used in cloud providers (AWS, Azure, GCP).
#
#
#
apiVersion: v1                    # Service API version
kind: Service                     # Resource type

metadata:
  name: <service-name>            # Service name
  namespace: <namespace>          # Namespace
  labels:                         # Service labels
    <key>: <value>

spec:
  type: ClusterIP                 # ClusterIP / NodePort / LoadBalancer / ExternalName

  selector:                       # Finds matching Pods
    <key>: <value>

  ports:
    - name: <port-name>           # Port identifier

      protocol: TCP               # TCP or UDP

      port: <service-port>        # Port exposed by Service

      targetPort: <container-port> # Port inside Pod

      nodePort: <node-port>       # Only for NodePort type

  externalName: <dns-name>        # Only for ExternalName type
#
#
#
#kubectl get svc
#kubectl describe svc <service-name>
#kubectl get endpoints
#kubectl get pods --show-labels
#kubectl describe pod <pod-name>